SQL_SUCCESS = 0
SQL_SUCCESS_WITH_INFO = 1
SQL_STILL_EXECUTING = 2
SQL_NEED_DATA = 99
SQL_NO_DATA = 100

SQL_NULL_DATA = -1
SQL_DATA_AT_EXEC = -2

SQL_PARAM_INPUT = 1
SQL_PARAM_INPUT_OUTPUT = 2
SQL_PARAM_OUTPUT = 4

SQL_NTS = -3

SQL_CLOSE = 0

SQL_UNKNOWN_TYPE = 0
SQL_CHAR = 1
SQL_NUMERIC = 2
SQL_DECIMAL = 3
SQL_INTEGER = 4
SQL_SMALLINT = 5
SQL_FLOAT = 6
SQL_REAL = 7
SQL_DOUBLE = 8
SQL_DATE = 9
SQL_TIME = 10
SQL_TIMESTAMP = 11
SQL_VARCHAR = 12
SQL_LONGVARCHAR = -1
SQL_BINARY = -2
SQL_VARBINARY = -3
SQL_LONGVARBINARY = -4
SQL_BIGINT = -5
SQL_TINYINT = -6
SQL_BIT = -7

SQL_TYPE_DATE = 91
SQL_TYPE_TIME = 92
SQL_TYPE_TIMESTAMP = 93

SQL_C_DEFAULT = 99
SQL_SIGNED_OFFSET = -20
SQL_UNSIGNED_OFFSET = -22

SQL_C_CHAR = SQL_CHAR
SQL_C_FLOAT = SQL_REAL
SQL_C_DOUBLE = SQL_DOUBLE
SQL_C_DATE = SQL_DATE
SQL_C_TIME = SQL_TIME
SQL_C_TIMESTAMP = SQL_TIMESTAMP
SQL_C_BIT = SQL_BIT
SQL_C_TINYINT = SQL_TINYINT
SQL_C_STINYINT = SQL_TINYINT + SQL_SIGNED_OFFSET
SQL_C_UTINYINT = SQL_TINYINT + SQL_UNSIGNED_OFFSET
SQL_C_SHORT = SQL_SMALLINT
SQL_C_SSHORT = SQL_C_SHORT + SQL_SIGNED_OFFSET
SQL_C_USHORT = SQL_C_SHORT + SQL_UNSIGNED_OFFSET
SQL_C_LONG = SQL_INTEGER
SQL_C_SLONG = SQL_C_LONG + SQL_SIGNED_OFFSET
SQL_C_ULONG = SQL_C_LONG + SQL_UNSIGNED_OFFSET
SQL_C_SBIGINT = SQL_BIGINT + SQL_SIGNED_OFFSET
SQL_C_UBIGINT = SQL_BIGINT + SQL_UNSIGNED_OFFSET

-- ODBCVER >= 0x0300
SQL_C_TYPE_DATE = SQL_TYPE_DATE
SQL_C_TYPE_TIME = SQL_TYPE_TIME
SQL_C_TYPE_TIMESTAMP = SQL_TYPE_TIMESTAMP
